[package]
name = "rj1it"
version = "0.1.0"
edition = "2021"

[dependencies]
mime_guess = "2.0.5"
reqwest = { version = "0.12.9", features = ["blocking", "multipart"] }
tokio = { version = "1.41.1", features = ["full"] }
